version: "3"
services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy-network
    depends_on:
      - stripe-react
      - backend
    restart: always

  stripe-react:
    build:
      context: .
    expose:
      - 3000
    networks:
      - proxy-network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    expose:
      - 3001
    networks:
      - proxy-network

networks:
  proxy-network:
